influxdata:
    image: tutum/influxdb
    command: "true"
    volumes:
        - /nar/influx:/data

influxdb:
    image: tutum/influxdb
    hostname: influxdb
    log_driver: "syslog"
    ports:
        - "8086:8086"
        - "8083:8083"
    volumes_from:
        - influxdata
    environment:
        INFLUXDB_VERSION: 0.9.4.1


api:
    build: .
    hostname: api
    command: ./startup.sh
    dns:
        - 172.16.24.105
        - 10.6.10.208
        - 8.8.8.8
        - 8.8.4.4
    volumes:
        - .:/app
        - ./config:/config
    expose:
        - "8000:8000"
    links:
        - influxdb:influx
    env_file:
        - .env


nginx:
    image: nginx:1.7
    links:
        - api:backend
    volumes:
        - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
        - .:/app
    ports:
        - "80:80"
