mongodata:
    image: mongo:2.6
    command: "true"
    volumes:
        - /nar/mongo:/mongo/data

mongodb:
    image: mongo:2.6
    hostname: mongodb
    command: "--dbpath=/mongo/data"
    #log_driver: "syslog"
    expose:
        - "27017:27017"
    volumes_from:
        - mongodata

influxdata:
    image: tutum/influxdb
    command: "true"
    volumes:
        - /nar/influx:/data

influxdb:
    image: tutum/influxdb
    hostname: influxdb
    #log_driver: "syslog"
    ports:
        - "8086:8086"
        - "8083:8083"
    volumes_from:
        - influxdata
    environment:
        INFLUXDB_VERSION: 0.9.4.1

basepython:
    build: .
    command: "true"
    volumes:
        - .:/app
        - ./config:/config
    dns:
        - 172.16.24.105
        - 10.6.10.208
        - 8.8.8.8
        - 8.8.4.4
    env_file:
        - .env

api:
    extends:
        service: basepython
    hostname: api
    command: ./startup.sh
    #log_driver: "syslog"
    expose:
        - "8000:8000"
    links:
        - mongodb:mongo
        - influxdb:influx


nginx:
    image: nginx:1.7
    #log_driver: "syslog"
    links:
        - api:backend
    volumes:
        - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
        - .:/app
    ports:
        - "80:80"
